/*
 * E-commerce API
 *
 * API for managing products, shopping carts, warehouse operations, and credit card processing
 *
 * API version: 1.0.0
 * Contact: support@example.com
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi

import (
	"net/http"
	"time"

	"github.com/gin-gonic/gin"
)

type PostOrderSyncAPI struct {
}

// Post /v1/products/:productId/details
// Add product details
func (api *PostOrderSyncAPI) PostOrderSync(c *gin.Context) {
	var order Order
	if err := c.ShouldBindJSON(&order); err != nil {
		c.JSON(http.StatusBadRequest, gin.H{"error": err.Error()})
		return
	}

	// Set order status to processing
	order.Status = "processing"

	// Simulate payment verification delay (3 seconds)
	time.Sleep(3 * time.Second)

	// After processing
	order.Status = "completed"
	order.CreatedAt = time.Now()

	c.JSON(http.StatusOK, order)
}
