/*
 * E-commerce API
 *
 * API for managing products, shopping carts, warehouse operations, and credit card processing
 *
 * API version: 1.0.0
 * Contact: support@example.com
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi

import (
	"github.com/gin-gonic/gin"
)

type ShoppingCartAPI struct {
}

// Post /v1/shopping-carts/:shoppingCartId/items
// Add items to shopping cart 
func (api *ShoppingCartAPI) AddItemsToCart(c *gin.Context) {
	// Your handler implementation
	c.JSON(200, gin.H{"status": "OK"})
}

// Post /v1/shopping-carts/:shoppingCartId/checkout
// Checkout shopping cart 
func (api *ShoppingCartAPI) CheckoutCart(c *gin.Context) {
	// Your handler implementation
	c.JSON(200, gin.H{"status": "OK"})
}

// Post /v1/shopping-carts
// Create a new shopping cart 
func (api *ShoppingCartAPI) CreateShoppingCart(c *gin.Context) {
	// Your handler implementation
	c.JSON(200, gin.H{"status": "OK"})
}

