/*
 * E-commerce API
 *
 * API for managing products, shopping carts, warehouse operations, and credit card processing
 *
 * API version: 1.0.0
 * Contact: support@example.com
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi

type ReserveInventoryRequest struct {

	// Unique identifier for the product
	ProductId int32 `json:"product_id"`

	// Quantity to reserve
	Quantity int32 `json:"quantity"`
}
