/*
 * E-commerce API
 *
 * API for managing products, shopping carts, warehouse operations, and credit card processing
 *
 * API version: 1.0.0
 * Contact: support@example.com
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi

type Error struct {

	// Error code
	Error string `json:"error"`

	// Human-readable error message
	Message string `json:"message"`

	// Additional error details
	Details string `json:"details,omitempty"`
}
