/*
 * E-commerce API
 *
 * API for managing products, shopping carts, warehouse operations, and credit card processing
 *
 * API version: 1.0.0
 * Contact: support@example.com
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi

type CheckoutCart200Response struct {

	// Unique identifier for the created order
	OrderId int32 `json:"order_id,omitempty"`
}
