/*
 * E-commerce API
 *
 * API for managing products, shopping carts, warehouse operations, and credit card processing
 *
 * API version: 1.0.0
 * Contact: support@example.com
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi

type ProcessPaymentRequest struct {

	// Credit card number (13-19 digits)
	CreditCardNumber string `json:"credit_card_number" validate:"regexp=^[0-9]{13,19}$"`

	// Unique identifier for the shopping cart
	ShoppingCartId int32 `json:"shopping_cart_id"`
}
