/*
 * E-commerce API
 *
 * API for managing products, shopping carts, warehouse operations, and credit card processing
 *
 * API version: 1.0.0
 * Contact: support@example.com
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi

type ProcessPayment200Response struct {

	// Whether the payment was successful
	Success bool `json:"success,omitempty"`

	// Unique transaction identifier
	TransactionId string `json:"transaction_id,omitempty"`
}
