/*
 * E-commerce API
 *
 * API for managing products, shopping carts, warehouse operations, and credit card processing
 *
 * API version: 1.0.0
 * Contact: support@example.com
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi

type CreateShoppingCart201Response struct {

	// Unique identifier for the created shopping cart
	ShoppingCartId int32 `json:"shopping_cart_id,omitempty"`
}
