/*
 * E-commerce API
 *
 * API for managing products, shopping carts, warehouse operations, and credit card processing
 *
 * API version: 1.0.0
 * Contact: support@example.com
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi

type Product struct {

	// Unique identifier for the product
	ProductId int32 `json:"product_id"`

	// Stock Keeping Unit - unique product code
	Sku string `json:"sku"`

	// Product manufacturer name
	Manufacturer string `json:"manufacturer"`

	// Product category identifier
	CategoryId int32 `json:"category_id"`

	// Product weight in grams
	Weight int32 `json:"weight"`

	// Additional identifier for product
	SomeOtherId int32 `json:"some_other_id"`
}
