/*
 * E-commerce API
 *
 * API for managing products, shopping carts, warehouse operations, and credit card processing
 *
 * API version: 1.0.0
 * Contact: support@example.com
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi

// ID, Name (searchable), Category (searchable), Description, Brand
type Product struct {

	// Unique identifier for the product
	ProductId int32 `json:"id"`

	// Product name
	ProductName string `json:"name"`

	// Product category
	Category string `json:"category"`

	// Product description
	Description string `json:"description"`

	// Product brand
	Brand string `json:"brand"`
}
