/*
 * E-commerce API
 *
 * API for managing products, shopping carts, warehouse operations, and credit card processing
 *
 * API version: 1.0.0
 * Contact: support@example.com
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi

type CreateShoppingCartRequest struct {

	// Unique identifier for the customer
	CustomerId int32 `json:"customer_id"`
}
